eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: #注意这里的defaultZone的写法，写成default-zone是不对的
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
