server:
  port: 8081

eureka:
  instance:
    hostname: eureka_server2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: #注意这里的defaultZone的写法，写成default-zone是不对的
      defaultZone: http://localhost:8080/eureka/
spring:
  devtools:
    restart:
      enabled: true
